### ISSUE TITLE
classad.ExprTree : weird slice operator behavior

### ISSUE THREAD

**Issue by mmascher** [bbockelm/python-classad#1]
Hi Brian,

there is something weird going on with the slice operator (unless I am not understanding something). Look ad this example, where I am trying to remove the `"` at the end of a classad:

```
(Pdb) self.task_ad.lookup('CRAB_ReqName')
"150423_074637:mmascher_crab_testecmmascher-dev6_158"
(Pdb) type(self.task_ad.lookup('CRAB_ReqName'))
<class 'classad.ExprTree'>
(Pdb) self.task_ad.lookup('CRAB_ReqName')[1:-1]
'50423_074637:mmascher_crab_testecmmascher-dev6_15'
```

It removes also the fisrt and last character. On the other hand if I use the classad value in my code doing `self.task_ad.lookup('CRAB_ReqName')`, I got the value with `"`.

So, the only to remove the `"` is to convert the classad to a string before slicing it:

```
(Pdb) str(self.task_ad.lookup('CRAB_ReqName'))
'"150423_074637:mmascher_crab_testecmmascher-dev6_158"'
(Pdb) str(self.task_ad.lookup('CRAB_ReqName'))[1:-1]
'150423_074637:mmascher_crab_testecmmascher-dev6_158'
```

I do not need it, the workaround of converting to string first works for me. But I think it is confusing.

PS I figured I could warn you using github instead of sending you an email.

**Comment by bbockelm** [comment]
Hm.  The `lookup` method returns an expression object without evaluating the expression.  Taking a slice of the expression will cause it to evaluate immediately.  In this case, it evaluates to a string and the slice is applied.

Here's a few other examples:

```
>>> ad = classad.ClassAd({"foo": "bar", "bar": classad.ExprTree("1+4"), "baz": [1,2,3,4]})
>>> ad
[ bar = 1 + 4; foo = "bar"; baz = { 1,2,3,4 } ]
>>> ad.lookup("foo")
"bar"
>>> ad.lookup("foo")[:]
'bar'
>>> ad.lookup("bar")
1 + 4
>>> ad.lookup("bar")[:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ClassAd expression is unsubscriptable.
```

In the end, if you want to cast ClassAd values to python values (and not throw an exception), you want to use the `get` method or explicitly evaluate the expression:

```
>>> ad.get("foo")
'bar'
>>> ad.get("fo")
>>> ad.get("bar")
1 + 4
>>> ad.lookup("foo")
"bar"
>>> ad.lookup("foo").eval()
'bar'
>>> ad.lookup("bar").eval()
5L
```

Note that the `get` method will only convert values (basic strings, integers, but not an expression) while `lookup`/`eval` will force evaluation.

**Comment by mmascher** [comment]
so that's the correct behavior? Imho it's confusing that this

```
(Pdb) str(self.task_ad.lookup('CRAB_ReqName'))[1:-1]
'150423_074637:mmascher_crab_testecmmascher-dev6_158'
```

and this:

```
(Pdb) self.task_ad.lookup('CRAB_ReqName')[1:-1]
'50423_074637:mmascher_crab_testecmmascher-dev6_15'
```

return different values. But on the other hand what you say makes sense (lookup evaluates, str does not). I was just trying to be a good "user" and report something I found confusing, thinking about the next non-Brian person who will use the library (and might get confused as I was :))

But close the issue if it's invalid.

**Comment by mmascher** [comment]
And thanks for the explanation!!

**Comment by bbockelm** [comment]
For a simpler case explaining things - 

```
>>> ad = classad.ClassAd({"foo": "bar"})
>>> ad.lookup("foo")
"bar"
>>> type(ad.lookup("foo"))
<class 'classad.ExprTree'>
>>> str(ad.lookup("foo"))
'"bar"'
>>> ad.lookup("foo")[:]
'bar'
>>> type(ad.lookup("foo")[:])
<type 'str'>
```

In other words, one returns the string representation of the expression object.  When doing the slice, we evaluate to a string first - hence you are taking a slice of the evaluated string.

Unfortunately, while expressions are a key concept in the ClassAd language, they aren't quite as central within Python.  This makes converting back and forth between languages sometimes awkward (as in this case).

**Comment by mmascher** [comment]
I see the point, thanks Brian.
